security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: emailAddress
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: /
                check_path: /
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout
                target: /
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_MANAGER: [ROLE_USER,ROLE_MANAGER]
        ROLE_OWNER: [ROLE_USER,ROLE_MANAGER,ROLE_OWNER]
        ROLE_ADMIN: [ROLE_USER,ROLE_MANAGER,ROLE_OWNER,ROLE_ADMIN]
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    encoders:
        App\Entity\Users:
            algorithm: 'native'